version: "3"
services:
  nodeapi:
    image: "node:latest"
    container_name: "nodejs"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes: 
      - .:/home/node/app
    ports:
      - "3000:3000"
    command: "npm run dev" 


  #MongoDB
  mongoapi:
    container_name: mongoApi
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"
    depends_on:
      - nodeapi

  web:
    container_name: nginxApi
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./aplicacion:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      
  # Configuración de php
  php-fpm:
    container_name: phpApi
    build: .
    volumes:
      - ./aplicacion:/var/www/html